version: '3.9'

services:
  app:
    build: .
    image: '${TEST_IMAGE}'
    ports:
      - '8080:50051'
    environment:
      RUN: test
      HOST: 'localhost'
      PORT: '50051'
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_USERNAME: 'user'
      RABBITMQ_PASSWORD: 'bitnami'
      REDIS_URL: 'redis://redis:6379'
      REDIS_USERNAME: ''
      REDIS_PASSWORD: ''
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - rabbitmq
      - redis
    networks:
      - app-tier

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: bitnami
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5672"
    networks:
      - app-tier


  redis:
    image: 'bitnami/redis:6.2.12'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
      - '6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - 'redis_data:/bitnami/redis/data'


networks:
  app-tier:
    driver: bridge

volumes:
  redis_data:
    driver: local