version: '3.9'

services:
  app:
    build: .
    image: 'app'
    ports:
      - '8080:50051'
    environment:
      RUN: test
      HOST: 'localhost'
      PORT: '50051'
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_USERNAME: 'user'
      RABBITMQ_PASSWORD: 'bitnami'
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - app-tier

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: bitnami
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5672"
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge
