apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway-app
spec:
  selector:
    matchLabels:
      app: api-gateway-app
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway
          image: ghcr.io/giveaway-mongo/api-gateway:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: api-gateway-configmap
          ports:
            - containerPort: 8080
              name: ag-port

