apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-configmap
data:
  RUN: "production"
  HOST: "localhost"
  PORT: "50051"
  DATABASE_URL: 'mongodb+srv://anvar_aka:mongodb@giveaway.axcgf0w.mongodb.net/test'
  RABBITMQ_HOST: 'rabbitmq-service'
  RABBITMQ_USERNAME: 'user'
  RABBITMQ_PASSWORD: 'bitnami'
  REDIS_URL: 'redis://redis:6379'
  REDIS_USERNAME: ''
  REDIS_PASSWORD: 'root123'